os: osx
osx_image: xcode11.5
language: swift
jobs:
  include:
    - stage: build and test
      script: fastlane scan --scheme MovieDB --device "iPhone 11 Pro Max" --clean --code_coverage
      if: (branch = master-rx) AND (NOT (type IN (push, pull_request)))

after_success:
 - bash <(curl -s https://codecov.io/bash) -J MovieDB